import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { invoke, isTauri } from '@tauri-apps/api/core';
import './style.css';

type Asset = { id: string; name: string; bytes: number };
type Operation = 'image' | 'encrypt' | 'decrypt' | 'documents' | 'license';
function App() {
  const [files,setFiles]=useState<Asset[]>([]),[selected,setSelected]=useState('');
  const [operation,setOperation]=useState<Operation>('image');
  const [password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[show,setShow]=useState(false);
  const [format,setFormat]=useState('png'),[edge,setEdge]=useState(0),[quality,setQuality]=useState(85);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const desktop=isTauri(), file=files.find(f=>f.id===selected);
  const supported=operation==='image'?/\.(png|jpg|jpeg|bmp)$/i.test(file?.name||''):operation==='decrypt'?/\.age$/i.test(file?.name||''):operation==='encrypt';
  const valid=!!file && supported && (operation==='image' || (operation==='decrypt'?password.length>0:[...password].length>=12 && password===confirm));
  function changeOperation(next:Operation){setOperation(next);setPassword('');setConfirm('');setMessage('');setError('');}
  async function add(){try{const added=await invoke<Asset[]>('pick_files');setFiles(previous=>[...previous,...added]);if(added[0])setSelected(added[0].id);}catch(e){setError(String(e));}}
  async function run(){setBusy(true);setError('');setMessage('Choose a new output filename in the save dialog.');try{setMessage(await invoke<string>('process_file',{id:selected,operation,password,format,maxEdge:edge,quality}));}catch(e){setError(String(e));setMessage('');}finally{setPassword('');setConfirm('');setBusy(false);}}
  return <><header><div className="brand"><b>d.</b> Doc Converter <span>Your documents. Your control.</span></div><small>Development build · 0.1.0</small></header><main>
    <p className="eyebrow">DOCUMENT WORKSPACE</p><h1>A new format. The same privacy.</h1><p className="subtitle">Local file processing. Original files are always kept.</p>
    {!desktop&&<div className="notice">Browser preview — open the desktop application to select and process local files.</div>}
    <nav aria-label="Workspace">{([['image','Images'],['encrypt','Encrypt'],['decrypt','Decrypt'],['documents','Documents'],['license','License']] as [Operation,string][]).map(([id,label])=><button key={id} disabled={busy} aria-pressed={operation===id} className={operation===id?'active':''} onClick={()=>changeOperation(id)}>{label}</button>)}</nav>
    {operation==='documents'?<section className="placeholder"><p className="eyebrow">NEXT ENGINE MILESTONE</p><h2>Document conversion & page layout</h2><p>LibreOffice and qpdf are not connected in this build. PDF conversion, merging, page breaks, landscape layout and PDF passwords are not available yet.</p><p>The design reference remains in the opendesign folder.</p></section>:operation==='license'?<section className="placeholder"><p className="eyebrow">DEVELOPMENT LICENSE</p><h2>Activation service not configured</h2><p>This development build is not licensed for commercial distribution. One-time activation, machine seats and signed offline authorizations are planned; no license server is contacted.</p><p>Do not enter a purchased license key here. Recovery and decryption will remain available independently of paid entitlements.</p></section>:<div className="workspace"><section className="queue"><div className="heading"><div><h2>Your files <span className="badge">{files.length}</span></h2><p>Select one file to process in this first build.</p></div><button onClick={add} disabled={busy||!desktop}>＋ Add files</button></div>
      {files.length?<ul>{files.map(f=><li key={f.id}><label><input type="radio" name="file" checked={selected===f.id} disabled={busy} onChange={()=>{setSelected(f.id);setMessage('');setError('');}}/><span><strong>{f.name}</strong><small>{(f.bytes/1024).toFixed(1)} KB</small></span></label><button aria-label={`Remove ${f.name}`} disabled={busy} onClick={()=>{setFiles(files.filter(x=>x.id!==f.id));if(selected===f.id)setSelected('');}}>×</button></li>)}</ul>:<button className="empty" disabled={!desktop||busy} onClick={add}><span>＋</span><strong>Add your first file</strong><small>{operation==='image'?'PNG, JPG and BMP':operation==='decrypt'?'Password-encrypted .age files':'Any document or file'}</small></button>}
      <p className="footnote">Files stay on this computer. Nothing is uploaded.</p></section><aside><p className="eyebrow">OUTPUT SETTINGS</p><h2>{operation==='image'?'Convert an image':operation==='encrypt'?'Protect a file':'Restore your file'}</h2>
      {operation==='image'?<><label>Output format<select disabled={busy} value={format} onChange={e=>setFormat(e.target.value)}><option value="png">PNG · lossless</option><option value="jpg">JPG · smaller files</option></select></label><label>Resize<select disabled={busy} value={edge} onChange={e=>setEdge(Number(e.target.value))}><option value={0}>Original dimensions</option>{[1920,1280,640].map(n=><option key={n} value={n}>Fit within {n} × {n}</option>)}</select></label><label>JPG quality · {quality}%<input disabled={busy||format!=='jpg'} type="range" min="1" max="100" value={quality} onChange={e=>setQuality(Number(e.target.value))}/></label><p className="hint">Aspect ratio is preserved. JPG uses white behind transparent pixels. Metadata is stripped. Colour-profile conversion is not implemented yet.</p></>:<><p className="info">{operation==='encrypt'?'Creates a standard .age encrypted copy. This is file encryption, not a PDF-open password.':'Restores the original bytes from a password-encrypted .age file.'}</p><label>{operation==='encrypt'?'Create a password':'File password'}<div className="password"><input disabled={busy} type={show?'text':'password'} autoComplete="off" value={password} onChange={e=>setPassword(e.target.value)}/><button disabled={busy} onClick={()=>setShow(!show)}>{show?'Hide':'Show'}</button></div></label>{operation==='encrypt'&&<><label>Confirm password<input disabled={busy} type={show?'text':'password'} autoComplete="off" value={confirm} onChange={e=>setConfirm(e.target.value)}/></label><p className="hint">At least 12 characters. Keep it safe; there is no password recovery.</p>{confirm&&confirm!==password&&<p className="error">Passwords do not match.</p>}</>}</>}
      {file&&!supported&&<p className="error">This file type is not supported for the selected operation.</p>}
      <div className="action"><p className="hint">Choose where to save a new copy. Existing files are never overwritten.</p><button className="primary" disabled={!desktop||busy||!valid} onClick={run}>{busy?'Working…':operation==='image'?'Convert image →':operation==='encrypt'?'Encrypt file →':'Decrypt file →'}</button>{busy&&<button onClick={()=>invoke('cancel_job').catch(e=>setError(String(e)))}>Cancel processing</button>}</div></aside></div>}
    <div aria-live="polite">{message&&<p className="notice">{message}</p>}{error&&<p role="alert" className="error notice">{error}</p>}</div><footer>Private by design <span>Rust + Tauri · Real processing, limited first milestone</span></footer>
  </main></>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
