import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const require = createRequire('C:/Users/wolfw/AppData/Local/Temp/opencode/package.json');
const { chromium } = require('playwright');
const directory = path.dirname(fileURLToPath(import.meta.url));
const browser = await chromium.launch({ executablePath: 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, reducedMotion: 'reduce' });
const errors = [];
const externalRequests = [];
page.on('pageerror', (error) => errors.push(error.message));
page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); });
page.on('request', (request) => { if (/^https?:/.test(request.url())) externalRequests.push(request.url()); });
const value = (expression) => page.evaluate(expression);
const click = (selector) => page.locator(selector).click();
const noOverflow = async () => assert.equal(await value(() => document.documentElement.scrollWidth <= innerWidth), true, 'No page-level horizontal overflow');
try {
  await page.goto(new URL('./index.html', import.meta.url).href);
  await page.screenshot({ path: path.join(directory, 'desktop-preview.png'), fullPage: true });
  assert.equal(await page.locator('#file-rows tr').count(), 4);
  assert.equal(await page.locator('#result').isVisible(), false);
  assert.equal(await page.locator('#password-options').isVisible(), false);
  await noOverflow();
  await click('#select-all');
  assert.equal(await page.locator('#run').isDisabled(), true);
  await click('#select-all');
  await page.locator('#batch-format').selectOption('TXT');
  assert.equal(await page.locator('#output-summary').textContent(), 'TXT');
  await click('#merge');
  assert.equal(await page.locator('#output-summary').textContent(), '1 combined PDF');
  assert.equal(await page.locator('#batch-format').isDisabled(), true);
  await click('#merge');
  assert.equal(await page.locator('.output-select').first().inputValue(), 'TXT');
  await page.locator('#batch-format').selectOption('PDF');
  await click('#advanced summary');
  await click('#watermark');
  await page.locator('#watermark-text').fill('Review copy');
  assert.equal(await page.locator('#paper-watermark').isVisible(), true);
  assert.equal(await page.locator('#paper-watermark').textContent(), 'Review copy');
  await click('#protect');
  assert.equal(await page.locator('#run').isDisabled(), true);
  await page.locator('#password').fill('demo phrase');
  await page.locator('#confirm-password').fill('different phrase');
  assert.equal(await page.locator('#run').isDisabled(), true);
  await page.locator('#confirm-password').fill('demo phrase');
  assert.equal(await page.locator('#run').isEnabled(), true);
  await click('[data-mode="images"]');
  assert.equal(await page.locator('#password').inputValue(), '');
  assert.equal(await page.locator('#run').isDisabled(), true);
  await click('#samples');
  assert.equal(await page.locator('#file-rows tr').count(), 3);
  assert.equal(await page.locator('#quality').isDisabled(), true);
  await page.locator('#batch-format').selectOption('JPG');
  assert.equal(await page.locator('#quality').isEnabled(), true);
  await click('[data-mode="clean"]');
  await click('#samples');
  assert.equal(await page.locator('#clean-options').isVisible(), true);
  assert.equal(await page.locator('#convert-options').isVisible(), false);
  await click('[data-mode="encrypt"]');
  await click('#samples');
  await page.locator('#security-type').selectOption('pdf');
  assert.match(await page.locator('#ready-summary').textContent(), /1 file ready · 2 skipped/);
  await page.locator('#password').fill('demo phrase');
  await page.locator('#confirm-password').fill('demo phrase');
  await click('#run');
  assert.equal(await page.locator('[data-mode="convert"]').isDisabled(), true);
  await page.waitForFunction(() => document.getElementById('result-action').textContent === 'Dismiss');
  assert.match(await page.locator('#result-description').textContent(), /Nothing was converted/);
  assert.equal(await page.locator('#password').inputValue(), '');
  await click('[data-mode="decrypt"]');
  await click('#samples');
  assert.equal(await page.locator('#confirm-wrap').isVisible(), false);
  await page.locator('#password').fill('demo phrase');
  await click('#run');
  await click('#result-action');
  assert.equal(await page.locator('#result-title').textContent(), 'Demo cancelled');
  await click('[data-mode="convert"]');
  await click('#clear');
  assert.equal(await page.locator('#run').isDisabled(), true);
  await page.locator('#file-input').setInputFiles({ name: '<script>alert(1)</script>.docx', mimeType: 'application/octet-stream', buffer: Buffer.from('not read by prototype') });
  assert.equal(await page.locator('.name').textContent(), '<script>alert(1)</script>.docx');
  assert.equal(await page.locator('#file-rows script').count(), 0);
  await click('#samples');
  await page.evaluate(() => { document.getElementById('advanced').open = false; });
  await click('[data-orientation="landscape"]');
  assert.match(await page.locator('#paper').getAttribute('class'), /landscape/);
  await click('[data-orientation="portrait"]');
  await click('#about');
  assert.equal(await page.locator('#about-dialog').isVisible(), true);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('#about-dialog').isVisible(), false);
  for (const width of [1920, 1440, 1280, 1024, 768, 390, 320]) {
    await page.setViewportSize({ width, height: 1000 });
    await noOverflow();
  }
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: path.join(directory, 'mobile-preview.png'), fullPage: true });
  assert.deepEqual(externalRequests, []);
  assert.deepEqual(errors, []);
  console.log('PASS: selection, formats, merge restoration, watermark, passwords, five modes, eligibility, completion, cancellation, safe filenames, dialog, seven viewport widths, no external requests, no browser errors.');
} finally {
  await browser.close();
}
